### ISSUE TITLE
Is the project still working? I would like to know if I can use jupyterlab 3.4.8 to work properly?

### ISSUE THREAD

**Issue by li1311139481** [aolney/jupyterlab-blockly-r-extension#8]

**Comment by aolney** [comment]
The project works with JupyterLab versions listed in the README. I plan on upgrading it to current versions of JupyterLab over the next year.

Explanation: the JupyterLab developers decided to change their graphics libraries between versions 1 and 2. This makes plugins written for previous versions incompatible with later versions.
